services:

#   frontend:
#     platform: linux/x86_64 #  para quem tem MAC
#     container_name: frontend
#     build: ./frontend
#     ports:
#       - 8080:8080
#     working_dir: /app/frontend
#     volumes:
#       - ./frontend:/app/frontend
#     tty: true
#     stdin_open: true
#     command: bash
#     restart: always
#     environment:
#       VUE_APP_TITLE: Cashforce
#       API_URL: http://localhost:3000
#     depends_on:
#       - backend
#     networks:
#       - virtual_wan_Front-to-Back
    
  backend:
    platform: linux/x86_64
    container_name: backend
    build: ./backend
    working_dir: /app/backend
    restart: always
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: sql_user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: cashforce_v3
      MYSQL_HOST: mariadb
      API_PORT: 3000
    networks:
      - virtual_wan_Front-to-Back
      - virtual_lan_Back-to-DB

  mariadb:
        build:
            context: .
            dockerfile: dev.dockerfile
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: cashforce_v3
            MYSQL_USER: sql_user
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306
        networks:
            - virtual_lan_Back-to-DB
networks:
# The presence of these objects is sufficient to define them
  virtual_wan_Front-to-Back: {}
  virtual_lan_Back-to-DB: {}