services:

  # frontend:
  #   image: node:16.18
  #   platform: linux/x86_64
  #   container_name: frontend
  #   build: ./frontend
  #   ports:
  #     - 8080:8080
  #   working_dir: /app/front-end
  #   volumes:
  #     - ./front-end:/app/front-end
  #   command: bash
  #   restart: always
  #   depends_on:
  #     - backend

  backend:
    image: node:16.18
    platform: linux/x86_64
    container_name: backend
    build: ./backend
    working_dir: /app/back-end
    restart: always
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: sql_user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: cashforce_v3
      MYSQL_HOST: mariadb
      API_PORT: 3000

  mariadb:
        build:
            context: .
            dockerfile: dev.dockerfile
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: cashforce_v3
            MYSQL_USER: sql_user
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306
